SKIPMOUNT=false
PROPFILESKIPMOUNT=false
PROPFILE=false
POSTFSDATA=SKIPMOUNT=false
PROPFILE=false
POSTFSDATA=SKIPMOUNT=false
PROPFILE=false
POSTFSDATA=false
LATESTARTSSKIPMOUNT=false
PROPFILE=false
POSTFSDATA=false
LATESTARTSERVICE=false
SKIPMOUNT=false
PROPFILE=false
POSTFSDATA=false
LATESTARTSERVICE=false
#BY @apmods @artistaproducer t.me/apmods
print_modname() {
	ui_print " "
	ui_print "  ****************************"
	ui_print "      ⚡ Debloat Universal ⚡"
	ui_print "         ⭐ Version 5  ⭐"
	ui_print "        Spotify: Diman Ap "
	ui_print "  ****************************"
	ui_print " "
}
#BY @apmods @artistaproducer t.me/apmods
MIUIREPLACE="
/system/product/priv-app/SetupWizardPrebuilt
/system/system_ext/priv-app/SetupWizard
/system/system_ext/priv-app/PixelSetupWizard
/system/product/priv-app/SetupWizardPrebuilt
/system/product/priv-app/PixelSetupWizard
/system/system_ext/priv-app/SetupWizard
/system/priv-app/SetupWizard
/system/product/priv-app/SetupWizardPrebuilt
/system/product/priv-app/SetupWizard
/system/system_ext/priv-app/SetupWizard
/system/product/priv-app/SetupWizard
/system/system_ext/priv-app/SetupWizard
/system/system_ext/priv-app/PixelSetupWizard
/system/product/data-app/GoogleNews
/system/product/data-app/Podcasts
/system/product/data-app/Videos
/system/product/data-app/wps_lite
/system/product/data-app/YTMusic
/system/data-app/MIMediaEditorGlobal
/system/app/MIUIVideoPlaye
/system/app/MIUIVideoPlayer
/system/app/MIUIMusicGlobal
/system/priv-app/MIUIMusicGlobal
/system/priv-app/MiuiGalleryGlobalExplore
/system/app/Compass
/system/priv-app/SoundRecorderTargetSdk30
/system/app/SolidExplorerUnlocker
/system/app/MiFitness
/system/app/SolidExplorer
/system/app/YoutubeVanced
/system/app/CovenantBR
/system/priv-app/MusicFX
/system/app/MiRadio
/system/app/Turbo
/system/priv-app/Turbo
/system/app/Email
/system/app/Videos
/system/priv-app/Videos
/system/app/Videos
/system/app/VideoPlayer
/system/priv-app/Videos
/system/app/Videos
/system/priv-app/Videos
/system/priv-app/MiuiVideo
/system/priv-app/MiuiMusic
/system/priv-app/Music
/system/app/YTProMicrog
/system/app/PrintSpooler
/system/app/MIRadioGlobalBuiltin
/system/app/MiuiScanner
/system/system_ext/priv-app/EmergencyInfo
/system/app/MIUIWeatherGlobal
/system/priv-app/MIUIWeather
/system/priv-app/Weather
/system/app/MIUIWeather
/system/app/Weather
/system/priv-app/MIUIWeatherGlobal
/system/product/priv-app/HotwordEnrollmentOKGoogleHEXAGON
/system/priv-app/MIUISoundRecorderTargetSdk30Global
/system/product/data-app/Drive
/system/product/data-app/Photos
/system/product/data-app/Duo
/system/priv-app/MIUIYellowPageGlobal
/system/data-app/MiCreditInStub
/system/data-app/XMRemoteController
/system/data-app/MIGalleryLockScreenGlobal
/system/data-app/MIBrowserGlobal
/system/product/priv-app/HotwordEnrollmentXGoogleHEXAGON
/system/product/app/SpeechServicesByGoogle
/system/priv-app/MIShareGlobal
/system/priv-app/MIService
/system/app/MiuiPrintSpoolerBeta
/system/app/MIUINotes
/system/app/MIUICompassGlobal
/system/app/MIDrop
/system/app/YouTube
/system/priv-app/YouTube
/system/app/YouTube
/system/priv-app/YouTube
/system/app/YouTube
/system/priv-app/YouTube
/system/product/app/YouTube
/system/product/priv-app/YouTube
/system/product/app/YouTube
/system/product/priv-app/YouTube
/system/product/app/YouTube
/system/product/priv-app/YouTube
/system/app/AiAsstVision
/system/app/AnalyticsCore
/system/app/facebook
/system/app/FrequentPhrase
/system/app/Health
/system/app/HybridAccessory
/system/app/HybridPlatform
/system/app/KSICibaEngine
/system/app/InMipay
/system/app/Joyose
/system/app/Lens
/system/app/mab
/system/app/MiGalleryLockscreen
/system/app/MiuiBugReport
/system/app/MiuiCompass
/system/app/MiuiDaemon
/system/app/MiuiFrequentPhrase
/system/app/MiuiGalleryLockscreen
/system/app/MSA
/system/app/NextPay
/system/app/Notes
/system/app/PlayAutoInstallStubApp
/system/app/VoiceAssistant
/system/app/VoiceTrigger
/system/app/WMServices
/system/app/wps-lite
/system/app/XMSFKeeper
/system/app/YouDaoEngine
/system/data-app/Gmail2
/system/data-app/MiRemote
/system/data-app/ShareMe
/system/etc/yellowpage
/system/priv-app/Browser
/system/priv-app/facebook
/system/priv-app/GlobalMinusScreen
/system/priv-app/MiBrowser
/system/priv-app/MiDrop
/system/priv-app/MiGame
/system/priv-app/MiMover
/system/priv-app/MiService
/system/priv-app/MiShare
/system/priv-app/MiuiBrowser
/system/priv-app/MiuiHealth
/system/priv-app/MiuiScanner
/system/priv-app/PartnerBookmarksProvider
/system/priv-app/SoundRecorder
/system/priv-app/YellowPage
/system/product/app/GooglePay
/system/product/priv-app/GoogleRestorePrebuilt
/system/system_ext/priv-app/Leaflet
/system/product/app/talkback
/system/product/app/GoogleTTS
/system/product/app/DevicePolicyPrebuilt
/system/product/priv-app/NovaBugreportWrapper
/system/system_ext/app/Papers
/system/product/app/OmniJaws
/system/product/app/XPerienceWallpapers
/system/app/Yunikon
/system/app/XPeriaWeather
/system/product/priv-app/QtiSoundRecorder
/system/app/AbleMusic
/system/product/priv-app/Velvet
/system/product/app/Velvet
/system/product/priv-app/Velvet
/system/priv-app/Velvet
/system/app/Velvet
/system/product/app/PrebuiltGmail
/system/product/app/Chrome-Stub
/system/product/app/Chrome
/system/product/priv-app/Chrome
/system/product/app/arcore
/system/app/arcore
/system/priv-app/arcore
/system/product/priv-app/arcore
/system/product/priv-app/WellbeingPrebuilt
/system/product/app/WellbeingPrebuilt
/system/app/WellbeingPrebuilt
/system/priv-app/WellbeingPrebuilt
/system/app/Notes
/system/priv-app/Notes
/system/app/Notes
/system/priv-app/Notes
/system/app/Notes
/system/priv-app/Notes
/system/product/app/Notes
/system/product/priv-app/Notes
/system/app/AiAsstVision
/system/app/AnalyticsCore
/system/app/BookmarkProvider
/system/app/BuiltInPrintService
/system/app/Calculator
/system/app/CarrierDefaultApp
/system/app/Cit
/system/app/CloudService
/system/app/com.miui.qr
/system/app/com.xiaomi.macro
/system/app/EasterEgg
/system/app/facebook-appmanager
/system/app/FidoAuthen
/system/app/FidoClient
/system/app/GooglePrintRecommendationService
/system/app/greenguard
/system/app/Health
/system/app/HybridAccessory
/system/app/HybridPlatform
/system/app/IdMipay
/system/app/InMipay
/system/app/Joyose
/system/app/Lens
/system/app/LiveWallpapersPicker
/system/app/mab
/system/app/mi_connect_service
/system/app/MiCloudSync
/system/app/MiGalleryLockscreen
/system/app/Mipay
/system/app/MiPicks
/system/app/MiPlayClient
/system/app/MiuiAccessibility
/system/app/MiuiBugReport
/system/app/MiuiCompass
/system/app/MiuiDaemon
/system/app/MSA
/system/app/MSA-Global
/system/app/Netflix_activation
/system/app/NextPay
/system/app/Notes
/system/app/OsuLogin
/system/app/PartnerBookmarksProvider
/system/app/PaymentService
/system/app/PlayAutoInstallStubApp
/system/app/PrintRecommendationService
/system/app/SogouInput
/system/app/TouchAssistant
/system/app/Traceur
/system/app/TranslationService
/system/app/TSMClient
/system/app/UPTsmService
/system/app/VoiceAssist
/system/app/VsimCore
/system/app/WAPPushManager
/system/app/wps_lite
/system/app/XiaomiSimActivateService
/system/app/XMCloudEngine
/system/app/XMSFKeeper
/system/app/YouDaoEngine
/system/priv-app/Browser
/system/priv-app/CellBroadcastServiceModulePlatform
/system/priv-app/CloudBackup
/system/priv-app/CloudServiceSysbase
/system/priv-app/facebook-installer
/system/priv-app/facebook-services
/system/priv-app/GameCenterGlobal
/system/priv-app/GlobalMinusScreen
/system/priv-app/GoogleTTS
/system/priv-app/MiBrowserGlobal
/system/priv-app/MiDrop
/system/priv-app/MiGameCenterSDKService
/system/priv-app/MiService
/system/priv-app/MiShare
/system/priv-app/MiuiBrowserGlobal
/system/priv-app/MiuiScanner
/system/priv-app/NewHome
/system/priv-app/ONS
/system/priv-app/ProxyHandler
/system/priv-app/QuickSearchBox
/system/priv-app/SoundRecorder
/system/priv-app/Tag
/system/priv-app/UserDictionaryProvider
/system/priv-app/VoiceCommand
/system/priv-app/VoiceTrigger
/system/priv-app/VoiceUnlock
/system/priv-app/YellowPage
/system/product/app/aiasst_service
/system/product/app/Chrome
/system/product/app/FM
/system/product/app/Gmail2
/system/product/app/GoogleOne
/system/product/app/GoogleTTS
/system/product/app/Maps
/system/product/app/remoteSimLockAuthentication
/system/product/app/talkback
/system/product/app/uimremoteclient
/system/product/app/uimremoteserver
/system/product/app/YouTube
/system/product/priv-app/AndroidAutoStub
/system/product/priv-app/EmergencyInfo
/system/product/priv-app/GoogleAssistant
/system/product/priv-app/HotwordEnrollmentOKGoogleCORTEXM4
/system/product/priv-app/HotwordEnrollmentXGoogleCORTEXM4
/system/product/priv-app/ims
/system/product/priv-app/Velvet
/system/product/priv-app/Wellbeing
/system/system_ext/app/FM
/system/vendor/app/Joyose
/system/vendor/app/SoterService
/system/vendor/data/app/Drive
/system/vendor/data/app/Duo
/system/vendor/data/app/Music2
/system/vendor/data/app/Photos
/system/vendor/data/app/wps_lite
/system/vendor/data/app/XMRemoteController
/system/priv-app/PersonalAssistant
/system/app/NotesGlobalStub
/system/app/CalculatorGlobalStub
/system/app/MiDropStub
/system/app/CompassGlobalStub
/system/priv-app/ScannerGlobalStub
/system/priv-app/SoundRecorderStub
/system/product/priv-app/GoogleRestore
/system/product/app/GlobalFashiongallery
/system/system_ext/priv-app/GoogleFeedback
/system/app/MiuiAudioMonitor
/system/app/GoogleOneTimeInitializer
/system/priv-app/GoogleOneTimeInitializer
/system/app/GoogleOneTimeInitializer
/system/priv-app/GoogleOneTimeInitializer
/system/app/GoogleOneTimeInitializer
/system/priv-app/GoogleOneTimeInitializer
/system/product/app/GoogleOneTimeInitializer
/system/product/priv-app/GoogleOneTimeInitializer
/system/app/GoogleFeedback
/system/priv-app/GoogleFeedback
/system/app/GoogleFeedback
/system/priv-app/GoogleFeedback
/system/app/GoogleFeedback
/system/priv-app/GoogleFeedback
/system/product/app/GoogleFeedback
/system/product/priv-app/GoogleFeedback
/system/app/GoogleAssistant
/system/priv-app/GoogleAssistant
/system/app/GoogleAssistant
/system/priv-app/GoogleAssistant
/system/app/GoogleAssistant
/system/priv-app/GoogleAssistant
/system/app/GoogleAssistant
/system/priv-app/GoogleAssistant
/system/app/GoogleAssistant
/system/priv-app/GoogleAssistant
/system/app/GoogleAssistant
/system/priv-app/GoogleAssistant
/system/product/app/GoogleAssistant
/system/product/priv-app/GoogleAssistant
/system/app/MiMoverGlobal
/system/priv-app/MiMoverGlobal
/system/priv-app/MiMover
/system/app/MiMoverGlobal
/system/priv-app/MiMoverGlobal
/system/app/MiMoverGlobal
/system/priv-app/MiMoverGlobal
/system/app/OneTimeInitializer
/system/priv-app/OneTimeInitializer
/system/app/OneTimeInitializer
/system/priv-app/OneTimeInitializer
/system/app/OneTimeInitializer
/system/priv-app/OneTimeInitializer
/system/app/MiuiFreeformService
/system/priv-app/MiuiFreeformService
/system/app/MiuiFreeformService
/system/priv-app/MiuiFreeformService
/system/app/MiuiFreeformService
/system/priv-app/MiuiFreeformService
/system/app/HotwordEnrollmentOKGoogleWCD9340
/system/priv-app/HotwordEnrollmentOKGoogleWCD9340
/system/app/HotwordEnrollmentOKGoogleWCD9340
/system/priv-app/HotwordEnrollmentOKGoogleWCD9340
/system/app/HotwordEnrollmentOKGoogleWCD9340
/system/priv-app/HotwordEnrollmentOKGoogleWCD9340
/system/priv-app/HotwordEnrollmentXGoogleWCD9340
/system/priv-app/HotwordEnrollmentXGoogleWCD9340
/system/app/HotwordEnrollmentXGoogleWCD9340
/system/priv-app/HotwordEnrollmentXGoogleWCD9340
/system/app/HotwordEnrollmentXGoogleWCD9340
/system/priv-app/HotwordEnrollmentXGoogleWCD9340
/system/app/GoogleRestore
/system/priv-app/GoogleRestore
/system/app/GoogleRestore
/system/priv-app/GoogleRestore
/system/app/GoogleRestore
/system/priv-app/GoogleRestore
/system/product/app/GoogleRestore
/system/product/priv-app/GoogleRestore
/system/product/app/GoogleRestore
/system/product/priv-app/GoogleRestore
/system/app/AntHalService
/system/priv-app/AntHalService
/system/app/AntHalService
/system/priv-app/AntHalService
/system/app/AntHalService
/system/priv-app/AntHalService
/system/app/MiPlayClient
/system/priv-app/MiPlayClient
/system/app/MiPlayClient
/system/priv-app/MiPlayClient
/system/app/MiPlayClient
/system/priv-app/MiPlayClient
/system/app/MiDrive
/system/priv-app/MiDrive
/system/app/MiDrive
/system/priv-app/MiDrive
/system/app/MiDrive
/system/priv-app/MiDrive
/system/app/CloudService
/system/priv-app/CloudService
/system/app/CloudService
/system/priv-app/CloudService
/system/app/CloudService
/system/priv-app/CloudService
/system/app/MiCloudSync
/system/priv-app/MiCloudSync
/system/app/MiCloudSync
/system/priv-app/MiCloudSync
/system/app/MiCloudSync
/system/priv-app/MiCloudSync
/system/app/PrintRecommendationService
/system/priv-app/PrintRecommendationService
/system/app/PrintRecommendationService
/system/priv-app/PrintRecommendationService
/system/app/PrintRecommendationService
/system/priv-app/PrintRecommendationService
/system/app/AnalyticsCore
/system/priv-app/AnalyticsCore
/system/app/AnalyticsCore
/system/priv-app/AnalyticsCore
/system/app/AnalyticsCore
/system/priv-app/AnalyticsCore
/system/app/EmergencyInfo
/system/priv-app/EmergencyInfo
/system/app/EmergencyInfo
/system/priv-app/EmergencyInfo
/system/app/EmergencyInfo
/system/priv-app/EmergencyInfo
/system/product/app/EmergencyInfo
/system/product/priv-app/HelpRtcPrebuilt
/system/product/priv-app/EmergencyInfo
/system/product/app/EmergencyInfo
/system/product/priv-app/EmergencyInfo
/system/product/app/EmergencyInfo
/system/product/priv-app/EmergencyInfo
/system/app/AndroidAutoStub
/system/priv-app/AndroidAutoStub
/system/app/AndroidAutoStub
/system/priv-app/AndroidAutoStub
/system/app/AndroidAutoStub
/system/priv-app/AndroidAutoStub
/system/product/app/AndroidAutoStub
/system/product/priv-app/AndroidAutoStub
/system/product/app/AndroidAutoStub
/system/product/priv-app/AndroidAutoStub
/system/product/app/AndroidAutoStub
/system/product/priv-app/AndroidAutoStub
/system/priv-app/PersonalAssistant
/system/priv-app/PersonalAssistantGlobal
/system/app/PersonalAssistant
/system/app/PersonalAssistantGlobal
/system/priv-app/PersonalAssistant
/system/priv-app/PersonalAssistantGlobal
/system/app/PersonalAssistant
/system/app/PersonalAssistantGlobal
/system/priv-app/PersonalAssistant
/system/priv-app/PersonalAssistantGlobal
/system/app/PersonalAssistant
/system/app/PersonalAssistantGlobal
/system/app/VoiceAssist
/system/priv-app/CloudBackup
/system/priv-app/Backup
/system/app/Backup
/system/priv-app/Backup
/system/app/Backup
/system/priv-app/Backup
/system/app/Backup
/system/product/app/VoiceAssist
/system/product/priv-app/CloudBackup
/system/product/priv-app/Backup
/system/product/app/Backup
/system/product/priv-app/Backup
/system/product/app/Backup
/system/product/priv-app/Backup
/system/product/app/Backup
/system/product/priv-app/CloudBackup
/system/product/priv-app/CloudBackup
/system/product/app/CloudBackup
/system/product/priv-app/CloudBackup
/system/product/app/CloudBackup
/system/product/priv-app/CloudBackup
/system/product/app/CloudBackup
/system/app/BasicDreams
/system/priv-app/BasicDreams
/system/app/BasicDreams
/system/priv-app/BasicDreams
/system/app/BasicDreams
/system/priv-app/BasicDreams
/system/app/BookmarkProvider
/system/priv-app/BookmarkProvider
/system/app/BookmarkProvider
/system/priv-app/BookmarkProvider
/system/app/BookmarkProvider
/system/priv-app/BookmarkProvider
/system/priv-app/Browser
/system/app/Browser
/system/priv-app/Browser
/system/priv-app/MiuiBrowserGlobal
/system/app/MiuiBrowserGlobal
/system/app/MiuiBrowserGlobal
/system/priv-app/MiuiBrowserGlobal
/system/priv-app/MiuiBrowserGlobal
/system/app/MiuiBrowserGlobal
/system/priv-app/MiBrowserGlobal
/system/app/MiBrowserGlobal
/system/app/MiBrowserGlobal
/system/priv-app/MiBrowserGlobal
/system/priv-app/MiBrowserGlobal
/system/app/MiBrowserGlobal
/system/app/Browser
/system/priv-app/Browser
/system/app/Browser
/system/app/BugReport
/system/app/MiuiBugReport
/system/priv-app/BugReport
/system/priv-app/MiuiBugReport
/system/app/BugReport
/system/app/MiuiBugReport
/system/priv-app/BugReport
/system/priv-app/MiuiBugReport
/system/app/BugReport
/system/app/MiuiBugReport
/system/priv-app/BugReport
/system/priv-app/MiuiBugReport
/system/app/BuiltInPrintService
/system/priv-app/BuiltInPrintService
/system/app/BuiltInPrintService
/system/priv-app/BuiltInPrintService
/system/app/BuiltInPrintService
/system/priv-app/BuiltInPrintService
/system/app/CatchLog
/system/priv-app/CatchLog
/system/app/CatchLog
/system/priv-app/CatchLog
/system/app/CatchLog
/system/priv-app/CatchLog
/system/app/Cit
/system/priv-app/Cit
/system/app/Cit
/system/priv-app/Cit
/system/app/Cit
/system/priv-app/Cit
/system/app/CloudPrint2
/system/priv-app/CloudPrint2
/system/app/CloudPrint2
/system/priv-app/CloudPrint2
/system/app/CloudPrint2
/system/priv-app/CloudPrint2
/system/priv-app/CloudServiceSysbase
/system/app/CloudServiceSysbase
/system/priv-app/CloudServiceSysbase
/system/app/CloudServiceSysbase
/system/priv-app/CloudServiceSysbase
/system/app/CloudServiceSysbase
/system/system_ext/priv-app/MatLog
/system/product/etc/sysconfig/google_exclusives_enable.xml
/system/etc/sysconfig/google_exclusives_enable.xml
/system/etc/sysconfig/Shift.xml
/system/etc/sysconfig/Notice
/system/product/etc/sysconfig/Shift.xml
/system/product/etc/sysconfig/Notice
/system/product/etc/sysconfig/pixel_experience_2019_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2018.xml
/system/product/etc/sysconfig/pixel_2016_exclusive.xml
/system/product/etc/sysconfig/nga.xml
/system/product/etc/sysconfig/pixel_experience_2018_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2017.xml
/system/product/etc/sysconfig/pixel_experience_2017_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2019.xml
/system/product/etc/sysconfig/pixel_experience_2020_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2020.xml
/system/product/etc/sysconfig/pixel_experience_2021_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2021.xml
/system/etc/sysconfig/pixel_experience_2019_midyear.xml
/system/etc/sysconfig/pixel_experience_2018.xml
/system/etc/sysconfig/pixel_2016_exclusive.xml
/system/etc/sysconfig/nga.xml
/system/etc/sysconfig/nexus.xml
/system/etc/sysconfig/pixel_experience_2018_midyear.xml
/system/etc/sysconfig/pixel_experience_2017.xml
/system/etc/sysconfig/pixel_experience_2017_midyear.xml
/system/etc/sysconfig/pixel_experience_2019.xml
/system/etc/sysconfig/pixel_experience_2020_midyear.xml
/system/etc/sysconfig/pixel_experience_2020.xml
/system/etc/sysconfig/pixel_experience_2021_midyear.xml
/system/etc/sysconfig/pixel_experience_2021.xml
/system/system_ext/etc/sysconfig/pixel_experience_2019_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2018.xml
/system/system_ext/etc/sysconfig/pixel_2016_exclusive.xml
/system/system_ext/etc/sysconfig/nga.xml
/system/system_ext/etc/sysconfig/nexus.xml
/system/system_ext/etc/sysconfig/pixel_experience_2018_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2017.xml
/system/system_ext/etc/sysconfig/pixel_experience_2017_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2019.xml
/system/system_ext/etc/sysconfig/pixel_experience_2020_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2020.xml
/system/system_ext/etc/sysconfig/pixel_experience_2021_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2021.xml
/system/product/etc/sysconfig/pixel_experience_2022_midyear.xml
/system/etc/sysconfig/pixel_experience_2022_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2022.xml
/system/etc/sysconfig/pixel_experience_2022.xml
"
AOSP_REPLACE="
/system/product/app/GalleryGo
/system/system_ext/app/Superiorwalls
/system/app/Superiorwalls
/system/system_ext/priv-app/Updates
/system/product/priv-app/ScribePrebuilt
/system/product/priv-app/PixelLiveWallpaperPrebuilt
/system/product/priv-app/HelpRtcPrebuilt
/system/system_ext/app/Photos
/system/system_ext/app/FM2
/system/system_ext/priv-app/FM2
/system/product/app/FM2
/system/product/priv-app/FM2
/system/app/FM2
/system/priv-app/FM2
/system/system_ext/priv-app/WellbeingPrebuilt
/system/system_ext/priv-app/GoogleRestore
/system/system_ext/priv-app/AndroidAutoStubPrebuilt
/system/product/priv-app/AndroidAutoStubPrebuilt
/system/product/app/GoogleTTS
/system/product/app/talkback
/system/system_ext/priv-app/EmergencyInfo
/system/product/priv-app/GoogleRestorePrebuilt
/system/product/priv-app/WellbeingPrebuilt
/system/product/priv-app/GoogleRestorePrebuilt
/system/product/app/Velvet
/system/product/priv-app/Velvet
/system/priv-app/Velvet
/system/app/Velvet
/system/product/app/PrebuiltGmail
/system/product/app/Chrome-Stub
/system/product/app/Chrome
/system/product/priv-app/Chrome
/system/product/app/arcore
/system/app/arcore
/system/priv-app/arcore
/system/product/priv-app/arcore
/system/product/priv-app/WellbeingPrebuilt
/system/product/app/WellbeingPrebuilt
/system/app/WellbeingPrebuilt
/system/priv-app/WellbeingPrebuilt
/system/product/priv-app/GoogleRestorePrebuilt
/system/system_ext/priv-app/Leaflet
/system/system_ext/priv-app/Music
/system/product/app/talkback
/system/product/app/GoogleTTS
/system/product/app/DevicePolicyPrebuilt
/system/product/priv-app/NovaBugreportWrapper
/system/system_ext/app/Papers
/system/product/app/XPerienceWallpapers
/system/app/Yunikon
/system/product/priv-app/QtiSoundRecorder
/system/app/AbleMusic
/system/product/priv-app/Velvet
/system/app/Abstruct
/system/app/BlissUpdater
/system/priv-app/BlissUpdater
/system/app/BasicDreams
/system/app/BlissPapers
/system/app/BookmarkProvider
/system/app/Browser
/system/app/Abstruct
/system/app/BasicDreams
/system/app/BlissPapers
/system/app/BookmarkProvider
/system/app/Browser
/system/app/Chromium
/system/app/ColtPapers
/system/app/EggGame
/system/app/Email
/system/app/Exchange2
/system/app/Gallery
/system/app/GugelClock
/system/app/Jelly
/system/app/Kiwi
/system/app/MiXplorer
/system/app/Music
/system/app/Partnerbookmark
/system/app/PartnerBookmark
/system/app/Phonograph
/system/app/PhotoTable
/system/app/RetroMusic
/system/app/VanillaMusic
/system/app/Via
/system/app/QPGallery
/system/priv-app/AudioFX
/system/priv-app/Eleven
/system/priv-app/MatLog
/system/priv-app/MusicFX
/system/priv-app/OmniSwitch
/system/priv-app/Snap
/system/priv-app/Tag
/system/priv-app/Via
/system/priv-app/VinylMusicPlayer
/system/system_ext/app/EmergencyInfo
/system/app/SimpleCalendar
/system/system_ext/priv-app/EmergencyInfo
/system/app/Abstruct
/system/app/BasicDreams
/system/app/BlissPapers
/system/app/BookmarkProvider
/system/app/Browser
/system/app/Chromium
/system/app/ColtPapers
/system/app/EggGame
/system/app/Email
/system/app/Exchange2
/system/app/Gallery
/system/app/Jelly
/system/app/Kiwi
/system/app/Aves
/system/app/StagWalls
/system/priv-app/MetroMusicPlayer
/system/app/MiXplorer
/system/app/Music
/system/app/Partnerbookmark
/system/app/PartnerBookmark
/system/app/Phonograph
/system/app/PhotoTable
/system/app/RetroMusic
/system/app/VanillaMusic
/system/app/Via
/system/app/QPGallery
/system/priv-app/AudioFX
/system/priv-app/Eleven
/system/priv-app/MatLog
/system/priv-app/MusicFX
/system/priv-app/OmniSwitch
/system/priv-app/Snap
/system/priv-app/Tag
/system/priv-app/Via
/system/priv-app/Gallery2
/system/priv-app/MatLog
/system/priv-app/Calendar
/system/app/SimpleCalendar
/system/app/Browser
/system/app/DuckDuckGo
/system/app/Jelly
/system/app/ViaBrowser
/system/priv-app/MusicFX
/system/priv-app/AudioFX
/system/priv-app/Snap
/system/app/SimpleGallery
/system/priv-app/stats
/system/priv-app/crDroidMusic
/system/app/Music
/system/app/crDroidMusic
/system/app/RetroMusicPlayer
/system/priv-app/RetroMusicPlayerPrebuilt
/system/app/RetroMusicPlayerPrebuilt
/system/app/Phonograph
/system/app/TilesWallpaper
/system/app/Email
/system/priv-app/Email
/system/app/CloudPrint
/system/product/priv-app/stats
/system/product/priv-app/SimpleGallery
/system/product/app/Chrome
/system/product/app/Abstruct
/system/product/priv-app/RecorderPrebuilt
/system/product/app/Maps
/system/product/app/AboutBliss
/system/product/app/BasicDreams
/system/product/app/BlissStatistics
/system/product/app/BookmarkProvider
/system/product/app/Browser
/system/product/app/Calendar
/system/product/app/Dashboard
/system/product/app/Email
/system/product/app/EmergencyInfo
/system/product/app/Etar
/system/product/app/Gallery
/system/product/app/Jelly
/system/product/app/Music
/system/product/app/Partnerbookmark
/system/product/app/PartnerBookmark
/system/product/app/PhotoTable
/system/product/app/Recorder
/system/product/app/RetroMusic
/system/product/app/SimpleGallery
/system/product/app/Via
/system/product/app/WallpaperZone
/system/product/app/QPGallery
/system/product/overlay/ChromeOverlay
/system/product/overlay/TelegramOverlay
/system/product/overlay/WhatsAppOverlay
/system/product/priv-app/AncientWallpaperZone
/system/product/priv-app/crDroidMusic
/system/product/priv-app/Eleven
/system/product/priv-app/EmergencyInfo
/system/product/priv-app/Gallery2
/system/product/priv-app/MatLog
/system/product/priv-app/MusicFX
/system/product/priv-app/OmniSwitch
/system/product/priv-app/SafetyHub
/system/product/priv-app/Snap
/system/product/priv-app/Tag
/system/product/priv-app/Via
/system/product/priv-app/VinylMusicPlayer
/system/product/app/AboutBliss
/system/product/app/BasicDreams
/system/product/app/BlissStatistics
/system/product/app/BookmarkProvider
/system/product/app/Browser
/system/product/app/Calendar
/system/product/app/Dashboard
/system/product/app/EasterEgg
/system/product/app/Email
/system/product/app/EmergencyInfo
/system/product/app/Gallery
/system/product/app/Jelly
/system/product/app/Music
/system/product/app/Partnerbookmark
/system/product/app/PartnerBookmark
/system/product/app/PhotoTable
/system/product/app/RetroMusic
/system/product/app/SimpleGallery
/system/product/app/Via
/system/product/app/WallpaperZone
/system/product/app/QPGallery
/system/product/overlay/ChromeOverlay
/system/product/overlay/TelegramOverlay
/system/product/overlay/WhatsAppOverlay
/system/product/priv-app/AncientWallpaperZone
/system/product/priv-app/crDroidMusic
/system/product/priv-app/Eleven
/system/product/priv-app/EmergencyInfo
/system/product/priv-app/Gallery2
/system/product/priv-app/MatLog
/system/product/priv-app/MusicFX
/system/product/priv-app/OmniSwitch
/system/product/priv-app/SafetyHub
/system/product/priv-app/Snap
/system/product/priv-app/Tag
/system/product/priv-app/Via
/system/product/priv-app/VinylMusicPlayer
/system/product/app/AboutBliss
/system/product/app/BasicDreams
/system/product/app/BlissStatistics
/system/product/app/BookmarkProvider
/system/product/app/Browser
/system/product/app/Calendar
/system/product/app/Dashboard
/system/product/app/Email
/system/product/app/EmergencyInfo
/system/product/app/Etar
/system/product/app/Gallery
/system/product/app/Jelly
/system/product/app/Music
/system/product/app/Partnerbookmark
/system/product/app/PartnerBookmark
/system/product/app/PhotoTable
/system/product/app/QtiSoundRecorder
/system/product/app/RetroMusic
/system/product/app/SimpleGallery
/system/product/app/Via
/system/product/app/WallpaperZone
/system/product/app/QPGallery
/system/product/overlay/ChromeOverlay
/system/product/overlay/TelegramOverlay
/system/product/overlay/WhatsAppOverlay
/system/product/priv-app/AncientWallpaperZone
/system/product/priv-app/crDroidMusic
/system/product/priv-app/Eleven
/system/product/priv-app/EmergencyInfo
/system/product/priv-app/Gallery2
/system/product/priv-app/MatLog
/system/product/priv-app/MusicFX
/system/product/priv-app/OmniSwitch
/system/product/priv-app/SafetyHub
/system/product/priv-app/Snap
/system/product/priv-app/Tag
/system/product/priv-app/Via
/system/product/priv-app/VinylMusicPlayer
/system/product/priv-app/TipsPrebuilt
/system/product/app/Drive
/system/product/app/WallpapersBReel2020
/system/product/priv-app/AncientWallpaperZone
/system/product/priv-app/ViaBrowser
/system/product/priv-app/HotwordEnrollmentOKGoogleHEXAGON
/system/product/priv-app/HotwordEnrollmentXGoogleHEXAGON
/system/product/app/WallpapersBReel2020a
/system/product/app/Jelly
/system/product/priv-app/GoogleRestore
/system/product/app/Tycho
/system/product/app/GalleryGoPrebuilt
/system/product/app/Photos
/system/product/app/Gallery2
/system/product/priv-app/Gallery2
/system/product/app/crDroidMusic
/system/product/priv-app/crDroidMusic
/system/product/app/RetroMusicPlayer
/system/product/priv-app/RetroMusicPlayer
/system/product/priv-app/Email
/system/product/app/Bromite
/system/product/app/Email
/system/product/app/Exchange2
/system/product/app/Calendar
/system/product/app/YouTube
/system/product/priv-app/WellbeingPrebuilt
/system/product/priv-app/Wellbeing
/system/product/priv-app/SafetyHubPrebuilt
/system/product/priv-app/AndroidMigratePrebuilt
/system/product/priv-app/AndroidAutoStub
/system/product/priv-app/AndroidAutoStubPrebuilt
/system/product/app/ExactCalculator
/system/product/priv-app/DuckDuckGo
/system/product/priv-app/SimpleCalendar
/system/system_ext/priv-app/AudioFX
/system/system_ext/app/EmergencyInfo
/system/system_ext/priv-app/Gallery2
/system/system_ext/priv-app/Snap
/system/product/app/GrapheneCamera
/system/product/app/OPWidget
/system/product/app/Videos
/system/product/app/YouTubeMusicPrebuilt
/system/system_ext/priv-app/MatLog
/system/product/priv-app/SetupWizardPrebuilt
/system/system_ext/priv-app/SetupWizard
/system/system_ext/priv-app/PixelSetupWizard
/system/product/priv-app/SetupWizardPrebuilt
/system/product/priv-app/PixelSetupWizard
/system/system_ext/priv-app/SetupWizard
/system/priv-app/SetupWizard
/system/product/priv-app/SetupWizardPrebuilt
/system/product/priv-app/SetupWizard
/system/system_ext/priv-app/SetupWizard
/system/product/priv-app/SetupWizard
/system/system_ext/priv-app/SetupWizard
/system/system_ext/priv-app/PixelSetupWizard
/system/product/etc/sysconfig/google_exclusives_enable.xml
/system/etc/sysconfig/google_exclusives_enable.xml
/system/etc/sysconfig/Shift.xml
/system/etc/sysconfig/Notice
/system/product/etc/sysconfig/Shift.xml
/system/product/etc/sysconfig/Notice
/system/product/etc/sysconfig/pixel_experience_2019_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2018.xml
/system/product/etc/sysconfig/pixel_2016_exclusive.xml
/system/product/etc/sysconfig/nga.xml
/system/product/etc/sysconfig/pixel_experience_2018_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2017.xml
/system/product/etc/sysconfig/pixel_experience_2017_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2019.xml
/system/product/etc/sysconfig/pixel_experience_2020_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2020.xml
/system/product/etc/sysconfig/pixel_experience_2021_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2021.xml
/system/etc/sysconfig/pixel_experience_2019_midyear.xml
/system/etc/sysconfig/pixel_experience_2018.xml
/system/etc/sysconfig/pixel_2016_exclusive.xml
/system/etc/sysconfig/nga.xml
/system/etc/sysconfig/nexus.xml
/system/etc/sysconfig/pixel_experience_2018_midyear.xml
/system/etc/sysconfig/pixel_experience_2017.xml
/system/etc/sysconfig/pixel_experience_2017_midyear.xml
/system/etc/sysconfig/pixel_experience_2019.xml
/system/etc/sysconfig/pixel_experience_2020_midyear.xml
/system/etc/sysconfig/pixel_experience_2020.xml
/system/etc/sysconfig/pixel_experience_2021_midyear.xml
/system/etc/sysconfig/pixel_experience_2021.xml
/system/system_ext/etc/sysconfig/pixel_experience_2019_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2018.xml
/system/system_ext/etc/sysconfig/pixel_2016_exclusive.xml
/system/system_ext/etc/sysconfig/nga.xml
/system/system_ext/etc/sysconfig/nexus.xml
/system/system_ext/etc/sysconfig/pixel_experience_2018_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2017.xml
/system/system_ext/etc/sysconfig/pixel_experience_2017_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2019.xml
/system/system_ext/etc/sysconfig/pixel_experience_2020_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2020.xml
/system/system_ext/etc/sysconfig/pixel_experience_2021_midyear.xml
/system/system_ext/etc/sysconfig/pixel_experience_2021.xml
/system/product/etc/sysconfig/pixel_experience_2022_midyear.xml
/system/etc/sysconfig/pixel_experience_2022_midyear.xml
/system/product/etc/sysconfig/pixel_experience_2022.xml
/system/etc/sysconfig/pixel_experience_2022.xml
"
#BY @apmods @artistaproducer t.me/apmods
on_install_miui() {
	ui_print "  🌀 Eliminando Apps 🕗"
	unzip -o "$ZIPFILE" 'system/*' -d $MODPATH >&2
	rm -f 'system/product/overlay'-d $MODPATH >&2
}
on_install_aosp() {
	ui_print "  🌀 Eliminando Apps 🕗"
	unzip -o "$ZIPFILE" 'system/*' -d $MODPATH >&2
	rm -f 'system/product/etc/sysconfig/google_elite_configs.xml'-d $MODPATH >&2
}
#BY @apmods @artistaproducer t.me/apmods
set_permissions() {
	set_perm_recursive $MODPATH 0 0 0755 0644
}
#BY @apmods @artistaproducer t.me/apmodsrtistaproducer t.me/apmods
#BY @apmods @artistaproducer t.me/apmods
